name: Export and Publish
on:
  workflow_dispatch:
jobs:
  setup:
    name: Set Up For Export
    runs-on: ubuntu-slim
    outputs:
      godot-version: ${{ steps.get-godot-version.outputs.version }}
      game-version: ${{ steps.get-game-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Get Godot version
        id: get-godot-version
        run: |
          query_start="config\/features=PackedStringArray\(\""
          query_end="\", \".*\"\)"
          grep_query="^$query_start[0-9]\.[0-9](\.[0-9])?$query_end$"
          version=$(grep --perl-regexp "$query_start" game/project.godot | sed --regexp-extended "s#$query_start|$query_end##g")
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Get game version
        id: get-game-version
        run: |
          query="config\/version="
          version=$(grep "$query" game/project.godot | sed --expression "s/$query//" --expression 's/\"//g')
          echo "version=$version" >> $GITHUB_OUTPUT
  export:
    name: Export Game (${{ matrix.target.channel }})
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:${{ needs.setup.outputs.godot-version }}
    needs: setup
    strategy:
      matrix:
        target:
          - channel: linux
            extension: x86_64
          - channel: osx
            extension: zip
          - channel: windows
            extension: exe
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          lfs: true
          submodules: true
          token: ${{ secrets.PAT }}
      - name: Set up export templates
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates ~/.config
          mv /root/.config/godot ~/.config/godot
          mv /root/.local/share/godot/export_templates/${{ needs.setup.outputs.godot-version }}.stable ~/.local/share/godot/export_templates/${{ needs.setup.outputs.godot-version }}.stable
      - name: Cache Godot imports folder
        uses: actions/cache@v6
        with:
          path: .godot
          key: godot-${{ secrets.ITCH_GAME }}-imports-${{ matrix.target.channel }}-${{ hashFiles('.godot') }}
          restore-keys: |
            godot-${{ secrets.ITCH_GAME }}-imports-${{ matrix.target.channel }}-
            godot-${{ secrets.ITCH_GAME }}-imports-
            godot-${{ secrets.ITCH_GAME }}-
            godot-
      - name: Export game
        run: |
          mkdir ${{ matrix.target.channel }} 
          godot --headless --path game --export-release "${{ matrix.target.channel }}" ../${{ matrix.target.channel }}/${{ secrets.ITCH_GAME }}-${{ needs.setup.outputs.game-version }}-${{ matrix.target.channel }}.${{ matrix.target.extension }}
  publish-release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: 
      - setup
      - export
    strategy:
      matrix:
        target:
          - channel: linux
          - channel: osx
          - channel: windows
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ matrix.target.channel }}
          path: ${{ matrix.target.channel }}
      - name: Publish release action
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ matrix.target.channel }}/*
          tag: ${{ needs.setup.outputs.game-version }}
  deploy-itch:
    name: Deploy to Itch.io
    runs-on: ubuntu-latest
    needs: 
      - setup
      - export
    strategy:
      matrix:
        target:
          - channel: linux
          - channel: osx
          - channel: windows
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ matrix.target.channel }}
          path: ${{ matrix.target.channel }}
      - name: Setup butler
        uses: remarkablegames/setup-butler@v3
      - name: Publish to Itch.io
        run: butler push ${{ matrix.target.channel }} ${{ secrets.ITCH_USER }}/${{ secrets.ITCH_GAME }}-${{ needs.setup.outputs.game-version }}:${{ matrix.target.channel }} --userversion ${{ needs.setup.outputs.game-version }}
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}